### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by artursoler** [epfl-lara/leon-web#26]
The hosted demo doesn't work, reporting two error messages:

```
Failed to connect

The Leon server appears to be unreachable right now.
Retrying in 22 seconds... 
```

```
Failed to connect

Leon failed to contact the mothership :(
It usually indicates that your firewall blocks traffic on websocket ports.
```

Sorry for opening an issue since that's not the optimal way of reporting this kind of error, but I didn't find any other way of contact with the team on the project pages.

Thanks for the project though, it looks really interesting!

**Comment by artursoler** [comment]
Regarding the firewall mention on the error, I tried accessing it from 2 different networks, and none of them (nor my computer) have a firewall installed.

**Comment by sumith1896** [comment]
Hi @ArturSoler, did you try using http://leondev.epfl.ch/ ?

**Comment by MikaelMayer** [comment]
I restarted leon again. This time I also launched a previous script in the background that automatically relaunch leon whenever it is stuck. Hopefully it will temporarily fix the issue.
